name: kubernetes-deployment
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      - AUTH_TOKE_SECRET=KclA2uLDpNBjnvjFUSfQ3Z1Jr7JJiNpww/ihQLPFVLQ3q9wkdzqg9Pd67kzyN/l+kP/lw5t1Q53jhOb5/cVCAg==
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      - MONGODB_CONNECTION_URI="mongodb+srv://itsrkator:Z0351$AlPhA@mongo-cluster.ostez.mongodb.net/users"
      - AUTH_API_HOST='auth:3000'
