name: 'docker-multi-container-deployments'

services:
  # mongodb:
  #   image: 'mongo'
  #   volumes:
  #     - data:/data/db
  #   env_file:
  #     - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env

# volumes:
#   data:
