name: '04-kubernetes-orchestrating-services'
services:
  client:
    build: ./client
    ports:
      - 5173:5173
  comments:
    build: ./comments
    ports:
      - 4001:4001
  event-bus:
    build: ./events-bus
    ports:
      - 4005:4005
  moderation:
    build: ./moderation
    ports:
      - 4003:4003
  posts:
    build: ./posts
    ports:
      - 4000:4000
  query:
    build: ./query
    ports:
      - 4002:4002
    depends_on:
      - event-bus
