apiVersion: v1
kind: Service
metadata:
  name: events-bus-service
spec:
  selector:
    app: events-bus
  type: ClusterIP
  ports:
    - name: events-bus
      protocol: TCP
      port: 4005
      targetPort: 4005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-bus
  template:
    metadata:
      labels:
        app: events-bus
    spec:
      containers:
        - name: events-bus
          image: rkatorjuliusworks/blog-microservices-events-bus
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
