name: kubernetes-networking
services:
  auth:
    build: ./auth-api
    ports:
      - '3000:3000'
  users:
    build: ./users-api
    ports:
      - '8080:8080'
  tasks:
    build: ./tasks-api
    ports:
      - '8000:8000'
    environment:
      - TASK_FOLDER=tasks